### ISSUE TITLE
How to visualize the point cloud?

### ISSUE THREAD

**Issue by liudaizong** [Gorilla-Lab-SCUT/GeoA3#5]

**Comment by Yuxin-Wen** [comment]
I guess MeshLab is a good choice. You can download it [here](https://www.meshlab.net/).

**Comment by liudaizong** [comment]
> I guess MeshLab is a good choice. You can download it [here](https://www.meshlab.net/).

Sorry for confusion. I mean how can I get the visualization results of sampled points like Figure 1&2 of your paper.

**Comment by Yuxin-Wen** [comment]
I'm still a little confused. If you mean how to get the adversarial point clouds, you can run the code; and if you mean how to get the 2D screenshot of the 3D points, you can use the "save snapshot" botton in the MeshLab.

**Comment by Yuxin-Wen** [comment]
I'm still a little confused. If you mean how to get the adversarial point clouds, you can run the code; and if you mean how to get the 2D screenshot of the 3D points, you can use the "save snapshot" button in the MeshLab.

**Comment by liudaizong** [comment]
> I'm still a little confused. If you mean how to get the adversarial point clouds, you can run the code; and if you mean how to get the 2D screenshot of the 3D points, you can use the "save snapshot" button in the MeshLab.

Thanks for your quick reply. I download the MeshLab but fail to open the .mat file.

**Comment by Yuxin-Wen** [comment]
I get it. MeshLab cannot open .mat file, it is binary MATLAB file. You can convert it into .ply/.xyz files through python, and then you can open it in MeshLab.

**Comment by liudaizong** [comment]
> I get it. MeshLab cannot open .mat file, it is binary MATLAB file. You can convert it into .ply/.xyz files through python, and then you can open it in MeshLab.

Thanks a lot!!!!
